# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Python(object):
    def setupUi(self, Python):
        Python.setObjectName("Python")
        Python.resize(800, 600)
        Python.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 170, 0);")
        self.centralwidget = QtWidgets.QWidget(Python)
        self.centralwidget.setObjectName("centralwidget")
        self.showButton = QtWidgets.QPushButton(self.centralwidget)
        self.showButton.setGeometry(QtCore.QRect(220, 30, 321, 61))
        self.showButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.showButton.setObjectName("showButton")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(220, 110, 321, 61))
        self.addButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.addButton.setObjectName("addButton")
        self.delButton = QtWidgets.QPushButton(self.centralwidget)
        self.delButton.setGeometry(QtCore.QRect(220, 190, 321, 61))
        self.delButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.delButton.setObjectName("delButton")
        self.show_idButton = QtWidgets.QPushButton(self.centralwidget)
        self.show_idButton.setGeometry(QtCore.QRect(220, 430, 321, 61))
        self.show_idButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.show_idButton.setObjectName("show_idButton")
        self.show_dateButton = QtWidgets.QPushButton(self.centralwidget)
        self.show_dateButton.setGeometry(QtCore.QRect(220, 350, 321, 61))
        self.show_dateButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.show_dateButton.setObjectName("show_dateButton")
        self.editButton = QtWidgets.QPushButton(self.centralwidget)
        self.editButton.setGeometry(QtCore.QRect(220, 270, 321, 61))
        self.editButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.editButton.setObjectName("editButton")
        self.main_exit = QtWidgets.QPushButton(self.centralwidget)
        self.main_exit.setGeometry(QtCore.QRect(220, 510, 321, 61))
        self.main_exit.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.main_exit.setObjectName("main_exit")
        Python.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Python)
        self.statusbar.setObjectName("statusbar")
        Python.setStatusBar(self.statusbar)

        self.retranslateUi(Python)
        QtCore.QMetaObject.connectSlotsByName(Python)

    def retranslateUi(self, Python):
        _translate = QtCore.QCoreApplication.translate
        Python.setWindowTitle(_translate("Python", "Заметки"))
        self.showButton.setText(_translate("Python", "Вывод всех заметок из файла"))
        self.addButton.setText(_translate("Python", "Добавление заметки"))
        self.delButton.setText(_translate("Python", "Удаление заметки"))
        self.show_idButton.setText(_translate("Python", "Показать заметку по id"))
        self.show_dateButton.setText(_translate("Python", "Выбор заметки по дате"))
        self.editButton.setText(_translate("Python", "Редактирование заметки"))
        self.main_exit.setText(_translate("Python", "Выйти"))
